In [2]:
import pandas as pd

In [1]:
measurements_timeseries = pd.read_csv("measurements_analysis_ready.csv")
visits_thyroid = pd.read_csv("visits_analysis_ready.csv")

NameError: name 'pd' is not defined

In [ ]:
measurements_timeseries.head()

,person_id,gender_concept_id,gender_clean,year_of_birth,age_at_measurement,age_group,race_concept_id,race_clean,ethnicity_concept_id,ethnicity_clean,...,ALT,Serum_Creatinine,Serum_Albumin,tsh,t3,t4,has_tsh,has_t3,has_t4,has_any_thyroid_test
0,894170912,8507,M,1982.0,43.0,35-49,8527,White,38003564,Not Hispanic or Latino,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0
1,191126884,8532,F,2003.0,22.0,18-34,0,Unknown,0,Unknown,...,NaN,0.93,NaN,NaN,NaN,NaN,0,0,0,0
2,101262469,8532,F,2013.0,12.0,0-17,8527,White,38003564,Not Hispanic or Latino,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0
3,908390849,8507,M,1966.0,59.0,50-64,8516,Black or African American,38003564,Not Hispanic or Latino,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0
4,939482390,8507,M,2007.0,18.0,18-34,8527,White,38003564,Not Hispanic or Latino,...,80.0,1.16,4.2,NaN,NaN,NaN,0,0,0,0

In [ ]:
measurements_timeseries.info()

<class 'pandas.DataFrame'>
RangeIndex: 2913028 entries, 0 to 2913027
Data columns (total 29 columns):
 #   Column                Dtype
---  ------                -----
 0   person_id             int64
 1   gender_concept_id     int64
 2   gender_clean          str
 3   year_of_birth         float64
 4   age_at_measurement    float64
 5   age_group             str
 6   race_concept_id       int64
 7   race_clean            str
 8   ethnicity_concept_id  int64
 9   ethnicity_clean       str
 10  measurement_date      str
 11  measurement_year      int64
 12  measurement_month     str
 13  weight                float64
 14  bmi                   float64
 15  triglycerides         float64
 16  hba1c                 float64
 17  Serum_Glucose         float64
 18  AST                   float64
 19  ALT                   float64
 20  Serum_Creatinine      float64
 21  Serum_Albumin         float64
 22  tsh                   float64
 23  t3                    float64
 24  t4                    float64
 25  has_tsh               int64
 26  has_t3                int64
 27  has_t4                int64
 28  has_any_thyroid_test  int64
dtypes: float64(14), int64(9), str(6)
memory usage: 644.5 MB

In [ ]:
visits_thyroid.head()

,person_id,gender_concept_id,gender,gender_clean,year_of_birth,age_at_visit,age_group,race,race_clean,ethnicity,...,visit_start_date,visit_end_date,visit_duration_days,same_day_visit_flag,long_visit_flag_7d,long_visit_flag_30d,office_related_flag,inpatient_related_flag,emergency_related_flag,telehealth_flag
0,924609883,8532,F,F,1956.0,69.0,65+,White,White,Not Hispanic or Latino,...,2025-11-21,2026-01-18,58.0,0,1,1,1,0,0,0
1,426015508,8532,F,F,1932.0,93.0,65+,White,White,Not Hispanic or Latino,...,2025-08-01,2025-08-03,2.0,0,0,0,1,0,0,0
2,178569665,8532,F,F,1979.0,46.0,35-49,Black or African American,Black or African American,Not Hispanic or Latino,...,2025-05-15,2025-06-08,24.0,0,1,0,0,0,0,1
3,749236674,8507,M,M,1964.0,61.0,50-64,White,White,Not Hispanic or Latino,...,2025-08-19,2025-09-20,32.0,0,1,1,1,0,0,0
4,82232424,8532,F,F,1994.0,31.0,18-34,Other,Other,Not Hispanic or Latino,...,2025-06-10,2025-08-23,74.0,0,1,1,1,0,0,0

In [ ]:
visits_thyroid.info()

<class 'pandas.DataFrame'>
RangeIndex: 179124 entries, 0 to 179123
Data columns (total 28 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   person_id                    179124 non-null  int64
 1   gender_concept_id            179124 non-null  int64
 2   gender                       179124 non-null  str
 3   gender_clean                 179124 non-null  str
 4   year_of_birth                178760 non-null  float64
 5   age_at_visit                 178760 non-null  float64
 6   age_group                    178760 non-null  str
 7   race                         179124 non-null  str
 8   race_clean                   179124 non-null  str
 9   ethnicity                    179124 non-null  str
 10  ethnicity_clean              179124 non-null  str
 11  snomed_condition_concept_id  179124 non-null  int64
 12  condition_description        179124 non-null  str
 13  condition_description_clean  179124 non-null  str
 14  visit_concept_id             179124 non-null  int64
 15  visit_type                   179124 non-null  str
 16  visit_type_clean             179124 non-null  str
 17  visit_type_group             179124 non-null  str
 18  visit_start_date             179124 non-null  str
 19  visit_end_date               179124 non-null  str
 20  visit_duration_days          179124 non-null  float64
 21  same_day_visit_flag          179124 non-null  int64
 22  long_visit_flag_7d           179124 non-null  int64
 23  long_visit_flag_30d          179124 non-null  int64
 24  office_related_flag          179124 non-null  int64
 25  inpatient_related_flag       179124 non-null  int64
 26  emergency_related_flag       179124 non-null  int64
 27  telehealth_flag              179124 non-null  int64
dtypes: float64(3), int64(11), str(14)
memory usage: 38.3 MB

## For OR group, we're focusing on **Thyroid Conditions Cohort**

### **Bloodwork values involved with Thyroid are:**

**1. TSH (Thyroid-Stimulating Hormone)**
- measures hormone from pituitary gland that signals the thyroid
- HIGH TSH = UNDERactive thyroid = HYPOthyroidism
- LOW TSH = OVEReactive thyroid = HYPERthyroidism

**2. Free T3 (Thyroxine)**
- Often checked if HYPERthyroidism is suspected
- T3 can be HIGH while T4 remains normal

**3. Free T4 (Triiodothyronine)**
- MAIN hormone produced by thyroid gland
- often measured to confirm TSH results or confirm the severity and cause of the thyroid
    - helps to distinguish btw SUBCLINICAL & OVERT thyroid dysfunction
    - If TSH abnormal --> a free T4 measures the UNBOUND, active thyroid hormone to determine IF dysfunction lies WITHIN the thyroid gland OR the pituitatry gland

- **How Free T4 confirms TSH findings:**
    1. *Elevated TSH + LOW T4* = confirms primary HYPOthyroidism (UNDERACTIVE thyroid gland)
    2. *Low TSH + HIGH T4* = confirms primary HYPERthyroidism (OVEREACTIVE thyroid gland)
    3. *Elevated TSH + NORMAL T4* = suggests SUBCLINICAL HYPOthyroidism
        - indicated that pituitary is ACTING but thyroid is NOT yet failing significantly
    4. *Low TSH + NORMAL T4* = suggests SUBCLINICAL HYPERthyroidism
        - OR sometimes NON-thyroidal illness

## Question 1:
### What visit types are most common for thyroid-related care, and are certain thyroid diagnoses more likely to appear in specific visit types?

In [ ]:
len(visits_thyroid)

179124

In [ ]:
visits_thyroid.columns

NameError: name 'visits_thyroid' is not defined