Importing pandas and opening a dataset

In [ ]:
import sqlalchemy
import psycopg2
import pandas as pd

print(sqlalchemy.__version__)

In [2]:
import sys, site
print("Python:", sys.version)
print("Executable:", sys.executable)
print("Prefix:", sys.prefix)
print("Site-packages:", site.getsitepackages() if hasattr(site, "getsitepackages") else "n/a")

Python: 3.12.12 (main, Dec  9 2025, 02:06:02) [GCC 12.2.0]
Executable: /usr/local/bin/python
Prefix: /usr/local
Site-packages: ['/usr/local/lib/python3.12/site-packages']

In [3]:
import sys
!{sys.executable} -m pip install -U pip
!{sys.executable} -m pip install sqlalchemy psycopg2-binary

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in /usr/local/lib/python3.12/site-packages (25.0.1)
Collecting pip
  Downloading pip-25.3-py3-none-any.whl.metadata (4.7 kB)
Downloading pip-25.3-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 14.3 MB/s eta 0:00:00
Installing collected packages: pip
Successfully installed pip-25.3
Defaulting to user installation because normal site-packages is not writeable
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.46-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.3.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.7 kB)
Collecting typing-extensions>=4.6.0 (from sqlalchemy)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Downloading sqlalchemy-2.0.46-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 36.0 MB/s  0:00:00
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 47.4 MB/s  0:00:00
Downloading greenlet-3.3.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (609 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 609.9/609.9 kB 24.9 MB/s  0:00:00
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: typing-extensions, psycopg2-binary, greenlet, sqlalchemy
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [sqlalchemy]4 [sqlalchemy]
Successfully installed greenlet-3.3.1 psycopg2-binary-2.9.11 sqlalchemy-2.0.46 typing-extensions-4.15.0

In [1]:
import sqlalchemy, psycopg2
print(sqlalchemy.__version__)

2.0.46

In [2]:
from sqlalchemy import create_engine, text
import pandas as pd

engine = create_engine(
    "postgresql+psycopg2://hi5304_user:hi5304@db:5432/hi5304"
)

with engine.connect() as conn:
    print(conn.execute(text("SELECT 1")).scalar())

1

In [3]:
cardio10 = pd.read_sql(
    "SELECT * FROM cardio10 LIMIT 20;",
    engine
)

cardio10

,id,age_days,sex,height,weight,sbp,diastolic,cholesterol,gluc,smoking,...,dm,egfr,bptreat,statin,uacr,sdi,hba1c,prevent_full_10yr_cvd,prevent_full_10yr_ascvd,prevent_full_10yr_hf
0,57792,14455,0,164,62,110,70,0,0,0,...,0,88,1,1,0.5,2,6.5,0.199410,0.657339,0.199410
1,17274,15452,0,156,48,110,70,0,0,0,...,0,80,0,1,1.0,1,5.4,0.208530,0.762402,0.208530
2,59931,15235,1,168,72,110,80,1,0,0,...,0,109,0,1,6.7,1,5.6,0.212875,0.828295,0.212875
3,72971,15370,1,178,78,110,70,0,0,0,...,0,100,0,1,4.8,1,5.6,0.215769,0.540801,0.215769
4,33519,15184,0,153,63,110,70,0,0,0,...,0,81,0,0,2.2,4,5.1,0.217907,0.323234,0.217907
5,52147,15354,1,171,77,120,80,0,0,0,...,0,119,0,1,1.5,1,6.4,0.218856,0.447099,0.218856
6,35807,14635,1,168,68,120,80,0,0,0,...,0,76,0,1,3.7,1,5.3,0.221457,0.255052,0.221457
7,64620,14542,0,155,67,110,70,0,0,0,...,0,65,0,0,6.0,6,5.9,0.249106,0.248927,0.249106
8,79749,10964,0,160,59,110,70,0,0,0,...,0,95,1,1,174.4,4,5.3,0.252480,0.523174,0.252480
9,72254,15145,1,160,70,120,80,0,0,0,...,0,89,0,0,11.4,1,4.5,0.257121,0.581944,0.257121
10,96496,14366,1,168,89,110,60,0,0,0,...,0,84,0,1,55.4,3,4.6,0.258728,0.666481,0.258728
11,65472,14510,0,165,65,110,70,0,0,0,...,0,86,0,0,18.0,1,4.9,0.259857,0.475259,0.259857
12,13097,14478,0,152,57,120,85,0,0,0,...,0,91,0,1,2.2,6,5.9,0.259943,0.646153,0.259943
13,98157,14345,0,164,85,130,80,0,0,0,...,0,69,0,1,2.5,3,4.5,0.260771,0.910711,0.260771
14,25927,14428,1,170,74,120,80,0,0,0,...,0,115,0,1,56.7,1,4.5,0.263389,0.302915,0.263389
15,27900,14713,1,175,83,120,80,0,0,0,...,0,78,0,0,6.8,2,5.7,0.265645,0.469920,0.265645
16,19131,15297,0,153,64,110,70,0,0,0,...,0,92,0,0,10.2,2,5.0,0.272018,0.479614,0.272018
17,8723,14726,1,165,64,120,90,0,0,0,...,0,108,0,1,6.6,8,5.2,0.274111,0.423211,0.274111
18,92817,14648,1,170,72,120,80,0,0,0,...,0,97,0,1,8.5,5,5.5,0.276819,0.349743,0.276819
19,4512,14676,0,173,86,110,70,0,0,0,...,0,97,0,1,15.9,2,6.2,0.283067,2.183835,0.283067

In [11]:
patients = pd.read_sql("SELECT * FROM patients ORDER BY patient_id;", engine)
patients.head()

,patient_id,first_name,last_name,date_of_birth,sex,race,ethnicity,zip_code
0,1001,John,Doe,1968-04-12,M,White,Non-Hispanic,75201
1,1002,Maria,Lopez,1975-09-30,F,Hispanic,Hispanic,75204
2,1003,James,Smith,1982-01-18,M,Black,Non-Hispanic,75080
3,1004,Linda,Chen,1990-06-05,F,Asian,Non-Hispanic,75024
4,1005,Robert,Johnson,1959-11-22,M,White,Non-Hispanic,75230

In [10]:

medications = pd.read_sql("SELECT * FROM medications;", engine)
medications.head()

,medication_id,patient_id,medication,dose,frequency,date_started,indication
0,1,1001,Lisinopril,10 mg,Once daily,2024-09-01,Hypertension
1,2,1002,Amlodipine,5 mg,Once daily,2024-08-20,Hypertension
2,3,1003,Metoprolol,50 mg,Twice daily,2024-09-10,Hypertension
3,4,1003,Atorvastatin,20 mg,Once daily,2024-09-10,Hyperlipidemia
4,5,1005,Losartan,50 mg,Once daily,2024-09-05,Hypertension

In [7]:
bp = pd.read_sql("SELECT * FROM bp_readings ORDER BY bp_id;", engine)
bp.head()

   bp_id  patient_id reading_date  systolic  diastolic  heart_rate  source
0      1        1001   2024-09-01       148         92          78  Clinic
1      2        1001   2024-10-01       142         88          76    Home
2      3        1001   2024-11-01       136         84          74    Home
3      4        1002   2024-09-15       132         82          70  Clinic
4      5        1002   2024-10-15       128         80          68    Home

In [8]:
query = """
SELECT
  p.patient_id,
  p.first_name,
  p.last_name,
  b.reading_date,
  b.systolic,
  b.diastolic,
  b.heart_rate,
  b.source,
  m.medication,
  m.dose,
  m.frequency
FROM patients p
LEFT JOIN bp_readings b ON p.patient_id = b.patient_id
LEFT JOIN medications m ON p.patient_id = m.patient_id
ORDER BY p.patient_id, b.reading_date;
"""
df = pd.read_sql(query, engine)
df.head(20)

,patient_id,first_name,last_name,reading_date,systolic,diastolic,heart_rate,source,medication,dose,frequency
0,1001,John,Doe,2024-09-01,148,92,78,Clinic,Lisinopril,10 mg,Once daily
1,1001,John,Doe,2024-10-01,142,88,76,Home,Lisinopril,10 mg,Once daily
2,1001,John,Doe,2024-11-01,136,84,74,Home,Lisinopril,10 mg,Once daily
3,1002,Maria,Lopez,2024-09-15,132,82,70,Clinic,Amlodipine,5 mg,Once daily
4,1002,Maria,Lopez,2024-10-15,128,80,68,Home,Amlodipine,5 mg,Once daily
5,1003,James,Smith,2024-09-10,150,96,82,Clinic,Atorvastatin,20 mg,Once daily
6,1003,James,Smith,2024-09-10,150,96,82,Clinic,Metoprolol,50 mg,Twice daily
7,1003,James,Smith,2024-10-10,146,94,80,Home,Atorvastatin,20 mg,Once daily
8,1003,James,Smith,2024-10-10,146,94,80,Home,Metoprolol,50 mg,Twice daily
9,1004,Linda,Chen,2024-09-20,118,76,66,Clinic,NaN,NaN,NaN
10,1005,Robert,Johnson,2024-09-05,140,90,75,Clinic,Losartan,50 mg,Once daily